server:
    port: 8080
    servlet.contextPath: /
    
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useLegacyDatetimeCode=false&serverTimezone=Europe/Istanbul&useSSL=false
    #url: jdbc:mysql://192.168.110.71:3306/akademikveri?useSSL=false
    username: test
    password: Test1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
     
staticfiles: 